# Herdr configuration
# Reference: https://herdr.dev/docs/configuration/

onboarding = false

[theme]
name = "catppuccin"

[keys]
prefix = "ctrl+x"

split_horizontal = "prefix+s"  

[ui]
confirm_close = false
mouse_capture = true
pane_borders = true
pane_gaps = false
prompt_new_tab_name = false

[ui.toast]
delivery = "terminal"

[ui.sound]
enabled = false

[experimental]
kitty_graphics = true
