export WIKI_HOME="$HOME/Development/Repos/Notes"
export BUGWARRIORRC="$HOME/.config/task/bugwarrior.toml"
export TASKRC="$HOME/.config/task/taskrc"
export TASKDATA="$HOME/Development/Repos/Tasks"
export TASKOPENRC="$HOME/.config/task/taskopenrc"
