# Model settings
model: azure/o4-mini

# Cache settings
cache-prompts: true

# Output settings
dark-mode: true
completion-menu-bg-color: #ced6f7
completion-menu-current-bg-color: #ced6f
completion-menu-color: #212139
completion-menu-current-color: #d65a00

# Other settings
vim: true
editor: nvim

read:
  - ~/.config/aider/Conventions.md
