import type { DateRange, GroupBy } from "./types.js";
import type { ToolEvent, UsageEvent } from "./session-reader.js";

export interface Metrics { input: number; cacheRead: number; cacheWrite: number; output: number; reasoning: number; totalTokens: number; cost: number; assistantTurns: number; toolCalls: number; toolErrors: number; subagentCalls: number; uniqueSessions: number; sessionDays: number; activeDurationMs: number; cacheReadRate?: number; freshInputRate?: number; toolErrorRate?: number; }
export interface Row { key: string; label?: string; project?: string; workflow?: string; models?: string[]; firstTimestampMs?: number; lastTimestampMs?: number; metrics: Metrics }
function empty(): Metrics { return { input: 0, cacheRead: 0, cacheWrite: 0, output: 0, reasoning: 0, totalTokens: 0, cost: 0, assistantTurns: 0, toolCalls: 0, toolErrors: 0, subagentCalls: 0, uniqueSessions: 0, sessionDays: 0, activeDurationMs: 0 }; }
function day(ms: number): string { const d = new Date(ms); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function rates(metrics: Metrics): Metrics { const prompt = metrics.input + metrics.cacheRead + metrics.cacheWrite; if (prompt) { metrics.cacheReadRate = metrics.cacheRead / prompt; metrics.freshInputRate = (metrics.input + metrics.cacheWrite) / prompt; } if (metrics.toolCalls) metrics.toolErrorRate = metrics.toolErrors / metrics.toolCalls; return metrics; }
export function filtered(events: UsageEvent[], range: DateRange): UsageEvent[] { return events.filter((event) => event.timestampMs >= range.startMs && event.timestampMs < range.endMs); }
export function aggregate(events: UsageEvent[], tools: ToolEvent[], range: DateRange, groupBy: GroupBy): Row[] {
	const selected = filtered(events, range); const selectedTools = tools.filter((event) => event.timestampMs >= range.startMs && event.timestampMs < range.endMs); const rows = new Map<string, Row>(); const sessions = new Map<string, { days: Set<string>; min: number; max: number }>();
	function key(event: UsageEvent): string { if (groupBy === "day") return day(event.timestampMs); if (groupBy === "model") return `${event.provider}/${event.model}`; if (groupBy === "session") return event.sessionId; if (groupBy === "thread") return event.threadId; if (groupBy === "project") return event.project; if (groupBy === "agent") return event.agentName; return event.workflow; }
	function rowFor(keyValue: string, event?: UsageEvent): Row { let row = rows.get(keyValue); if (!row) { row = { key: keyValue, label: groupBy === "session" ? event?.sessionTitle || keyValue : groupBy === "thread" ? event?.threadTitle || keyValue : keyValue, project: event?.project, workflow: event?.workflow, models: [], metrics: empty() }; rows.set(keyValue, row); } return row; }
	for (const event of selected) { const row = rowFor(key(event), event); const m = row.metrics; m.input += event.input; m.cacheRead += event.cacheRead; m.cacheWrite += event.cacheWrite; m.output += event.output; m.reasoning += event.reasoning; m.totalTokens += event.totalTokens; m.cost += event.cost; m.assistantTurns++; row.models = Array.from(new Set([...(row.models ?? []), `${event.provider}/${event.model}`])); row.firstTimestampMs = Math.min(row.firstTimestampMs ?? event.timestampMs, event.timestampMs); row.lastTimestampMs = Math.max(row.lastTimestampMs ?? event.timestampMs, event.timestampMs); const s = sessions.get(event.sessionId) ?? { days: new Set<string>(), min: event.timestampMs, max: event.timestampMs }; s.days.add(day(event.timestampMs)); s.min = Math.min(s.min,event.timestampMs); s.max=Math.max(s.max,event.timestampMs); sessions.set(event.sessionId,s); }
	for (const event of selectedTools) { const matching = selected.find((usage) => usage.sessionId === event.sessionId); if (!matching) continue; const row = rowFor(key(matching), matching); row.metrics.toolCalls++; if (event.isError) row.metrics.toolErrors++; if (event.toolName === "subagent") row.metrics.subagentCalls++; }
	for (const row of rows.values()) { const constituent = groupBy === "session" ? [row.key] : Array.from(sessions.keys()).filter((id) => selected.some((event) => event.sessionId === id && key(event) === row.key)); row.metrics.uniqueSessions = constituent.length; row.metrics.sessionDays = constituent.reduce((sum,id)=>sum+(sessions.get(id)?.days.size ?? 0),0); row.metrics.activeDurationMs = constituent.reduce((sum,id)=>sum+((sessions.get(id)?.max ?? 0)-(sessions.get(id)?.min ?? 0)),0); rates(row.metrics); }
	return Array.from(rows.values()).sort((a,b) => groupBy === "day" ? a.key.localeCompare(b.key) : b.metrics.cost-a.metrics.cost || a.key.localeCompare(b.key));
}
export function anomalies(rows: Row[]): { rows: Row[]; insufficientSample: boolean; median?: number } { const eligible=rows.filter((row)=>row.metrics.cost>=0.25); if(eligible.length<4)return {rows:[],insufficientSample:true}; const values=eligible.map((row)=>row.metrics.cost).sort((a,b)=>a-b); const middle=Math.floor(values.length/2); const median=values.length%2 ? values[middle]! : (values[middle-1]!+values[middle]!)/2; return {rows:eligible.filter((row)=>row.metrics.cost>=2*median),insufficientSample:false,median}; }
