import type { DateRange, GroupBy, OutputFormat, SortOrder, UsageQuery, UsageSort } from "./types.js";
const GROUPS: GroupBy[] = ["day", "model", "session", "thread", "project", "workflow", "agent"];
function fail(message: string): never { throw new Error(`[--usage] ${message}`); }
function dateStart(value: string): number { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) fail(`Invalid date '${value}'; use YYYY-MM-DD.`); const [y,m,d]=value.split("-").map(Number); const result=new Date(y!,m!-1,d!); if(result.getFullYear()!==y||result.getMonth()!==m!-1||result.getDate()!==d) fail(`Invalid date '${value}'; use YYYY-MM-DD.`); return result.getTime(); }
function month(value: string): DateRange { if(!/^\d{4}-\d{2}$/.test(value)) fail(`Invalid period '${value}'; use YYYY-MM.`); const [y,m]=value.split("-").map(Number); const start=new Date(y!,m!-1,1); if(start.getFullYear()!==y||start.getMonth()!==m!-1) fail(`Invalid period '${value}'; use YYYY-MM.`); return {label:value,startMs:start.getTime(),endMs:new Date(y!,m!,1).getTime()}; }
function defaultRange(now: Date): DateRange { return month(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`); }
function positive(value: string, option: string): number { if(!/^\d+$/.test(value)||Number(value)<1) fail(`${option} must be a positive integer.`); return Number(value); }
function value(argv:string[], index:number, option:string):string { const result=argv[index+1]; if(!result||result.startsWith("--")) fail(`${option} requires a value.`); return result; }
function dimensions(raw: string, option: string): GroupBy[] { const result = raw.split(",").map((item) => item.trim() as GroupBy); if (!result.length || result.some((item) => !GROUPS.includes(item)) || new Set(result).size !== result.length) fail(`${option} accepts unique comma-separated: ${GROUPS.join(", ")}.`); return result; }
export function parseUsageQuery(argv:string[], now=new Date()): UsageQuery {
 let period:string|undefined,from:string|undefined,to:string|undefined,last:string|undefined,groupRaw:string|undefined,sumRaw:string|undefined,format:OutputFormat="text",limit=20,anomalies=false,detailed=false,help=false,usage=false,sortBy:UsageSort="cost",order:SortOrder="desc";
 for(let i=0;i<argv.length;i++){const arg=argv[i]!; if(arg==="--usage") usage=true; else if(arg==="--usage=help") {usage=true;help=true;} else if(arg.startsWith("--usage=")) fail("Use --usage with --group-by, --format, or --anomalies; run --usage=help."); else if(arg==="--period") period=value(argv,i++,"--period"); else if(arg==="--from") from=value(argv,i++,"--from"); else if(arg==="--to") to=value(argv,i++,"--to"); else if(arg==="--last") last=value(argv,i++,"--last"); else if(arg==="--group-by") groupRaw=value(argv,i++,"--group-by"); else if(arg==="--sum"){if(sumRaw!==undefined)fail("--sum may be specified once; use a comma-separated list.");sumRaw=value(argv,i++,"--sum");} else if(arg.startsWith("--group")) fail(`Unknown usage selector '${arg}'; use --group-by.`); else if(arg.startsWith("--sum")) fail(`Unknown usage selector '${arg}'; use --sum.`); else if(arg==="--format"){const v=value(argv,i++,"--format") as OutputFormat;if(!(["text","json","csv"] as string[]).includes(v))fail("--format must be text, json, or csv.");format=v;} else if(arg==="--sort"){const v=value(argv,i++,"--sort") as UsageSort;if(!(["cost","tokens","turns","cache-rate"] as string[]).includes(v))fail("--sort must be cost, tokens, turns, or cache-rate.");sortBy=v;} else if(arg==="--order"){const v=value(argv,i++,"--order") as SortOrder;if(!(["asc","desc"] as string[]).includes(v))fail("--order must be asc or desc.");order=v;} else if(arg==="--limit")limit=positive(value(argv,i++,"--limit"),"--limit"); else if(arg==="--anomalies")anomalies=true; else if(arg==="--detailed")detailed=true; }
 if(!usage) fail("Missing --usage."); const selectors=Number(Boolean(period))+Number(Boolean(from||to))+Number(Boolean(last));if(selectors>1)fail("Use only one range selector: --period, --from/--to, or --last.");if(Boolean(from)!==Boolean(to))fail("--from and --to must be used together.");let range=defaultRange(now);if(period)range=month(period);else if(from&&to){const startMs=dateStart(from),end=dateStart(to);if(end<startMs)fail("--to must not be before --from.");const d=new Date(end);range={label:`${from}..${to}`,startMs,endMs:new Date(d.getFullYear(),d.getMonth(),d.getDate()+1).getTime()};}else if(last){const match=/^(\d+)d$/i.exec(last);if(!match)fail("--last must use ND, e.g. 7d.");const n=positive(match[1]!,"--last"),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());range={label:`last ${n}d`,startMs:new Date(today.getFullYear(),today.getMonth(),today.getDate()-n+1).getTime(),endMs:new Date(today.getFullYear(),today.getMonth(),today.getDate()+1).getTime()};}
 const groupBy=groupRaw?dimensions(groupRaw,"--group-by"):[]; const sums=sumRaw?dimensions(sumRaw,"--sum"):[]; if(sums.length){if(!groupBy.length)fail("--sum requires --group-by.");for(const sum of sums){const index=groupBy.indexOf(sum);if(index<0)fail(`--sum dimension '${sum}' must occur in --group-by.`);if(index===groupBy.length-1)fail(`--sum dimension '${sum}' must have a descendant dimension.`);}if(format!=="text")fail("--sum currently supports --format text only.");}if(format==="csv"&&groupBy.length>1)fail("CSV supports one --group-by level only.");return{range,limit,groupBy,sums,format,anomalies,detailed,help,sortBy,order};
}
export function usageHelp():string{return ["Pi local usage analytics","  pi --usage [--period YYYY-MM | --from YYYY-MM-DD --to YYYY-MM-DD | --last ND]","  pi --usage --group-by thread,agent,model --sum agent,thread","  pi --usage --group-by model,session --format json","  pi --usage --group-by model --format csv","  pi --usage --anomalies --group-by project,session","  pi --usage=help","Group dimensions: day, model, session, thread, project, workflow, agent.","--sum is one comma-separated list of non-leaf group dimensions; text reports only.","Session titles are native Pi names: pi --name \"…\" or /name ….","Documentation: ~/.pi/agent/extensions/usage/README.md"].join("\n");}
