import type { Row } from "./analytics.js";
import type { DateRange } from "./types.js";

export function formatToken(value: number): string { return value >= 1_000_000 ? `${(value / 1_000_000).toFixed(1)}M` : value >= 10_000 ? `${Math.round(value / 1_000)}k` : value >= 1_000 ? `${(value / 1_000).toFixed(1)}k` : `${Math.round(value)}`; }
function pct(value?: number): string { return value === undefined ? "-" : `${(value * 100).toFixed(1)}%`; }
function csv(value: unknown): string { const text = value === undefined || value === null ? "" : String(value); return /[",\n]/.test(text) ? `"${text.replaceAll('"','""')}"` : text; }
export function textReport(title: string, rows: Row[], range: DateRange, limit = rows.length): string {
	const headers=["Key","Sessions","Turns","Input","C.Read","C.Write","Output","Reason","Cost","Cache"];
	const selected=rows.slice(0,limit); const raw=selected.map((row)=>[row.key,`${row.metrics.uniqueSessions}`,`${row.metrics.assistantTurns}`,formatToken(row.metrics.input),formatToken(row.metrics.cacheRead),formatToken(row.metrics.cacheWrite),formatToken(row.metrics.output),formatToken(row.metrics.reasoning),`$${row.metrics.cost.toFixed(4)}`,pct(row.metrics.cacheReadRate)]); const widths=headers.map((header,index)=>Math.max(header.length,...raw.map((row)=>row[index]!.length))); const format=(row:string[])=>row.map((cell,index)=>index===0?cell.padEnd(widths[index]!):cell.padStart(widths[index]!)).join("  ");
	return [`${title} (${range.label})`,"Cost is Pi-recorded estimate; aggregate output excludes prompt, response and tool content.",format(headers),widths.map((width)=>"-".repeat(width)).join("  "),...raw.map(format),selected.length===0?"No usage recorded for selected range.":""].filter(Boolean).join("\n");
}
export function jsonReport(mode: string, range: DateRange, rows: Row[], quality: Record<string, number>): string { return JSON.stringify({ schemaVersion: 1, mode, range: { label: range.label, startMs: range.startMs, endMs: range.endMs }, dataQuality: quality, rows }, null, 2); }
export function csvReport(rows: Row[]): string { const headers=["key","project","workflow","models","uniqueSessions","sessionDays","assistantTurns","toolCalls","toolErrors","subagentCalls","activeDurationMs","input","cacheRead","cacheWrite","output","reasoning","totalTokens","cost","cacheReadRate","freshInputRate","toolErrorRate"]; const lines=[headers.join(",")]; for(const row of rows){const m=row.metrics; lines.push([row.key,row.project,row.workflow,(row.models??[]).join(";"),m.uniqueSessions,m.sessionDays,m.assistantTurns,m.toolCalls,m.toolErrors,m.subagentCalls,m.activeDurationMs,m.input,m.cacheRead,m.cacheWrite,m.output,m.reasoning,m.totalTokens,m.cost,m.cacheReadRate,m.freshInputRate,m.toolErrorRate].map(csv).join(","));} return lines.join("\n"); }
