import { formatToken } from "./render.js";
import type { GroupBy, SortOrder, UsageSort } from "./types.js";
import type { UsageEvent } from "./session-reader.js";
export interface TreeNode { key:string; label:string; cost:number; input:number; cacheRead:number; cacheWrite:number; output:number; reasoning:number; turns:number; children:TreeNode[]; }
function value(event:UsageEvent, group:GroupBy):string { if(group==="day"){const d=new Date(event.timestampMs);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;} if(group==="model")return `${event.provider}/${event.model}`;if(group==="session")return event.sessionTitle || event.sessionId;if(group==="project")return event.project;if(group==="workflow")return event.workflow;return event.agentName; }
function score(node:TreeNode, sort:UsageSort):number{if(sort==="cost")return node.cost;if(sort==="turns")return node.turns;if(sort==="tokens")return node.input+node.cacheRead+node.cacheWrite+node.output;if(sort==="cache-rate"){const prompt=node.input+node.cacheRead+node.cacheWrite;return prompt?node.cacheRead/prompt:-1;}return 0;}
export function usageTree(events:UsageEvent[], startMs:number,endMs:number,groups:GroupBy[],sort:UsageSort="cost",order:SortOrder="desc"):TreeNode[]{const selected=events.filter(e=>e.timestampMs>=startMs&&e.timestampMs<endMs);const root=new Map<string,TreeNode>();for(const event of selected){let map=root;let parent:TreeNode|undefined;for(const group of groups){const label=value(event,group);let node=map.get(label);if(!node){node={key:label,label,cost:0,input:0,cacheRead:0,cacheWrite:0,output:0,reasoning:0,turns:0,children:[]};map.set(label,node);if(parent)parent.children.push(node);}node.cost+=event.cost;node.input+=event.input;node.cacheRead+=event.cacheRead;node.cacheWrite+=event.cacheWrite;node.output+=event.output;node.reasoning+=event.reasoning;node.turns++;parent=node;map=new Map(node.children.map(c=>[c.key,c]));}}const sign=order==="asc"?1:-1;const arrange=(nodes:TreeNode[]):TreeNode[]=>nodes.sort((a,b)=>sign*(score(a,sort)-score(b,sort))||a.label.localeCompare(b.label)).map(n=>({...n,children:arrange(n.children)}));return arrange([...root.values()]);}
export function renderTree(nodes:TreeNode[],depth=0,limit=Number.POSITIVE_INFINITY):string[]{const lines:string[]=[];for(const node of nodes.slice(0,limit)){lines.push(`${"  ".repeat(depth)}${node.label}  $${node.cost.toFixed(4)}  turns:${node.turns}`);lines.push(...renderTree(node.children,depth+1,limit));}return lines;}
function title(group:GroupBy):string{return group==="day"?"Date":group[0]!.toUpperCase()+group.slice(1);}
export function renderTreeTable(nodes:TreeNode[],groups:GroupBy[],limit:number):string{const rows:string[][]=[];const visit=(items:TreeNode[],path:string[])=>{for(const node of items.slice(0,limit)){const next=[...path,node.label];if(node.children.length)visit(node.children,next);else rows.push([...next,`$${node.cost.toFixed(4)}`,`${node.turns}`,`${formatToken(node.input)}`,`${formatToken(node.cacheRead)}`,`${formatToken(node.cacheWrite)}`,`${formatToken(node.output)}`,`${formatToken(node.reasoning)}`]);}};visit(nodes,[]);const headers=[...groups.map(title),"Cost","Turns","Input","C.Read","C.Write","Output","Reason"];const widths=headers.map((h,i)=>Math.max(h.length,...rows.map(r=>(r[i]??"").length)));const format=(r:string[])=>r.map((v,i)=>i===0?v.padEnd(widths[i]!):v.padStart(widths[i]!)).join("  ");return [format(headers),widths.map(w=>"-".repeat(w)).join("  "),...rows.map(format)].join("\n");}
