repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [ pre-commit ]
      - id: check-json
        stages: [ pre-commit ]
      - id: check-xml
        stages: [ pre-commit ]
      - id: check-yaml
        stages: [ pre-commit ]
      - id: no-commit-to-branch
        args: [ --branch, master ]
        stages: [ pre-commit ]
