repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [ pre-commit ]
      - id: check-json
        stages: [ pre-commit ]
      - id: check-xml
        stages: [ pre-commit ]
      - id: check-yaml
        stages: [ pre-commit ]
      - id: no-commit-to-branch
        args: [ --branch, master ]
        stages: [ pre-commit ]
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format --include
        types: [ "c#" ]
        stages: [ pre-push ]
      - id: dotnet-test
        name: dotnet-test
        language: system
        entry: dotnet test
        types_or: [ "c#", "csproj" ]
        pass_filenames: false
        stages: [ pre-push ]
      - id: dotnet-outdated
        name: dotnet-outdated
        language: system
        entry: dotnet outdated -f -vl Major -exc coverlet
        pass_filenames: false
        stages: [ pre-push ]
