[general]
import = [ "~/.config/alacritty/catppuccin-macchiato.toml" ]

[window]
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[window.padding]
x = 10
y = 10

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
