
name: Build and Push Docker Image

on:
  push:
    tags: # Trigger the workflow only when a tag is pushed
      - '*' # Matches all tags (e.g., v1.0.0, 1.0.0, etc.)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Extract the Git tag
    - name: Get Git Tag
      id: vars
      run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image with the Git tag as version
    - name: Build Base Docker image
      run: |
        docker build -t eckii24/dev-base:${{ env.TAG }} -t eckii24/dev-base:latest -f ./.config/setup-scripts/base.Dockerfile .

    # Push the Docker image to Docker Hub
    - name: Push Base Docker image
      run: |
        docker push eckii24/dev-base:${{ env.TAG }}
        docker push eckii24/dev-base:latest

